name: test
on: push
jobs: 
  test: 
    runs-on: ubuntu-latest
    steps: 
      - run: echo "hello"
      - run: pip install nbconvert
      - uses: actions/checkout@v4
      - run: sudo apt-get install pandoc texlive-xetex
      - run: python -m nbconvert --to pdf --execute lab_01/pint_and_boiling_point.ipynb
      - uses: actions/upload-artifact@v4
        with:
          path: lab_01/pint_and_boiling_point.pdf
